"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

final_space = true
version = 2

[console_title_template]
template = "{{ .Folder }}"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  type = "session"
  style = "diamond"
  foreground = "#ffbebc"
  leading_diamond = "<#ff70a6> \ue200 </>"
  template = "{{ .UserName }} <#ffffff>on</>"
  [blocks.segments.properties]
  display_host = true

  [[blocks.segments]]
  type = "time"
  style = "diamond"
  foreground = "#bc93ff"
  template = " {{ .CurrentDate | date .Format }} "
  [blocks.segments.properties]
  time_format = "Monday <#ffffff>at</> 3:04 PM"

  [[blocks.segments]]
  type = "git"
  style = "diamond"
  foreground = "#ee79d1"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
  [blocks.segments.properties]
  branch_icon = "\ue725 "
  fetch_stash_count = true
  fetch_status = true
  fetch_upstream_icon = true
  fetch_worktree_count = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#a9ffb4"

  [[blocks.segments]]
  type = "executiontime"
  style = "diamond"
  foreground = "#a9ffb4"
  template = " {{ .FormattedMs }}s <#ffffff>\ue601</>"
  [blocks.segments.properties]
  style = "dallas"
  threshold = 0

  [[blocks.segments]]
  type = "root"
  style = "diamond"
  template = " \uf0e7 "
  [blocks.segments.properties]
  root_icon = "\uf292 "

  [[blocks.segments]]
  type = "sysinfo"
  style = "diamond"
  foreground = "#94ffa2"
  template = " <#ffffff>MEM:</> {{ round .PhysicalPercentUsed .Precision }}% ({{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB)"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  type = "path"
  style = "diamond"
  foreground = "#ffafd2"
  leading_diamond = "<#00c7fc> \ue285 </><#ffafd2>{</>"
  template = " \ue5ff {{ .Path }} "
  trailing_diamond = "<#ffafd2>}</>"
  [blocks.segments.properties]
  folder_icon = "\uf07b"
  folder_separator_icon = " \uebcb "
  home_icon = "home"
  style = "agnoster_full"

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "#A9FFB4"
  template = " \ue286 "
  foreground_templates = ["{{ if gt .Code 0 }}#ef5350{{ end }}"]
  [blocks.segments.properties]
  always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "#FEF5ED"
template = "\ue285 "

