version = 2
final_space = true
terminal_background = "p:t-background"

[palette]
main-bg = "#24283b"
terminal-red = "#f7768e"
pistachio-green = "#9ece6a"
terminal-green = "#73daca"
terminal-yellow = "#e0af68"
terminal-blue = "#7aa2f7"
celeste-blue = "#b4f9f8"
light-sky-blue = "#7dcfff"
terminal-white = "#c0caf5"
white-blue = "#a9b1d6"
blue-bell = "#9aa5ce"
pastal-grey = "#cfc9c2"
terminal-magenta = "#bb9af7"
blue-black = "#565f89"
terminal-black = "#414868"
t-background = "p:main-bg"

[console_title_template]
template = " {{ .Folder }} {{if .Root}}:: Admin{{end}}"

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  background = "transparent"
  foreground = "p:terminal-blue"
  template = "\u279c "

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "p:terminal-magenta"
  template = "<b>{{ .PWD }}</b> <p:light-sky-blue>\u26a1</>"
  [blocks.segments.properties]
  style = "folder"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:light-sky-blue"
  template = "({{ .HEAD }})"
  [blocks.segments.properties]
  fetch_status = true
  branch_icon = "\ue725 "
  [blocks.segments.foreground_templates]
  templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ else }}p:light-sky-blue{{ end }}",
    "{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}",
    "{{ if gt .Behind 0 }}p:celeste-blue{{ end }}"
  ]

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "p:terminal-red"
  template = " \uf00d"

[[blocks]]
alignment = "right"
overflow = "hide"
type = "prompt"

  [[blocks.segments]]
  type = "node"
  style = "plain"
  foreground = "p:pistachio-green"
  template = "\ue718 {{ .Full }} "

  [[blocks.segments]]
  type = "php"
  style = "plain"
  foreground = "p:terminal-blue"
  template = "\ue73d {{ .Full }} "

  [[blocks.segments]]
  type = "python"
  style = "plain"
  foreground = "p:terminal-yellow"
  template = "\uE235 {{ .Full }}"

  [[blocks.segments]]
  type = "julia"
  style = "plain"
  foreground = "p:terminal-magenta"
  template = "\uE624 {{ .Full }}"

  [[blocks.segments]]
  type = "ruby"
  style = "plain"
  foreground = "p:terminal-red"
  template = "\uE791 {{ .Full}}"

  [[blocks.segments]]
  type = "go"
  style = "plain"
  foreground = "p:light-sky-blue"
  template = "\uFCD1 {{ .Full}}"

  [[blocks.segments]]
  type = "command"
  style = "plain"
  foreground = "p:white-blue"
  [blocks.segments.properties]
  command = "git log --pretty=format:%cr -1 || date +%H:%M:%S"
  shell = "bash"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "p:pistachio-green"
  style = "plain"
  template = "\u25b6"
  type = "text"

[secondary_prompt]
background = "transparent"
foreground = "p:terminal-blue"
template = "\u279c "

[transient_prompt]
background = "p:t-background"
foreground = "p:terminal-blue"
template = "\u279c "

